### ISSUE TITLE
Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'libRTIMULibWrapper.so'

### ISSUE THREAD

**Issue by LMtx** [johannesegger/SenseHatNet#4]
Hello,

I got `Unhandled Exception: System.DllNotFoundException: Unable to load DLL 'libRTIMULibWrapper.so'` when executing `docker run` with following Main function:

        static void Main(string[] args)
        {
            //TestLedMessage(args.Length > 0 ? args[0] : "Hello World");
            // TestLowLight();
            // TestJoystick();
            TestRTIMULib();
        }

`TestLedMessage` works without any issues, I've got troubles only with `TestRTIMULib`.

I created Docker image according to your [Sample](https://github.com/johannesegger/SenseHatNet/tree/master/Sample).

Do you have any idea what might be wrong?

My setup:
`Docker version 3.0.2, build e042b58f`
`RPi 3: Linux raspberrypi 4.14.98-v7+ #1200 SMP Tue Feb 12 20:27:48 GMT 2019 armv7l GNU/Linux`

**Comment by johannesegger** [comment]
Thanks for reporting.

It's a long time since I touched the native part of this library.
The exception is typically thrown when the library doesn't exist (which I doubt is the case here) or doesn't fit to the processor architecture. `libRTIMULibWrapper` is built using docker (see [here](https://github.com/johannesegger/SenseHatNet/blob/master/RTIMULib-dev/Dockerfile)) which uses the ARM cross compiler toolchain.

I can try rebuilding `libRTIMULibWrapper` with the latest version of the toolchain and publish a new version with it. You might as well be able to do so: Build `libRTIMULibWrapper` on your machine and then replace the original dll with it. Hope that helps.

**Comment by LMtx** [comment]
I will try rebuilding on Monday but please take a look at this issue - any help is very welcome :)

**Comment by johannesegger** [comment]
I'll see my RPi on Tuesday again, though I'm not sure if I have the time to do some tests.

**Comment by LMtx** [comment]
I would be grateful if you could check following (`ldd` executed inside docker container from Sample build image):

```
root@f79e1d9175ec:/usr/app# ldd libRTIMULibWrapper.so        
linux-vdso.so.1 (0x7eb17000)        
libRTIMULib.so.7 => not found        
libstdc++.so.6 => /usr/lib/arm-linux-gnueabihf/libstdc++.so.6 (0x76ea1000)        
libm.so.6 => /lib/arm-linux-gnueabihf/libm.so.6 (0x76e29000)      
libgcc_s.so.1 => /lib/arm-linux-gnueabihf/libgcc_s.so.1 (0x76e00000)        
libc.so.6 => /lib/arm-linux-gnueabihf/libc.so.6 (0x76d12000)        
/lib/ld-linux-armhf.so.3 (0x76fbf000)
```
 I wonder if you have `libRTIMULib.so.7 => not found` as well?

**Comment by johannesegger** [comment]
Hm I guess that never worked in a docker container because SenseHatNet doesn't ship `libRTIMULib.so.7`. It might have worked for me when `libRTIMULib.so.7` was installed globally. However SenseHatNet v0.0.5 now ships a copy of `libRTIMULib.so.7` and with it I get the following output (I realized I don't need physical access to my RPi to test this kind of stuff):

```
Settings file not found. Using defaults and creating settings file
Failed to open I2C bus 1
Failed to open SPI bus 0, select 0
Failed to open SPI bus 0, select 1
No IMU detected
Using fusion algorithm RTQF
Failed to open SPI bus 0, select 1
No pressure sensor detected
Failed to open SPI bus 0, select 1
No humidity sensor detected
Timestamp: 2534-02-22T20:42:45.5410000
FusionPose: Valid: True, Value: <0, 0, 0>
FusionQPose: Valid: True, Value: {X:0 Y:0 Z:0 W:1}
Gyro: Valid: False, Value: <0, 0, 0>
Accel: Valid: True, Value: <0, 0, 0>
Compass: Valid: True, Value: <0, 0, 0>
```

Still doesn't look entirely correct, but I guess it's a start. Can you try pulling the latest version from GitHub and running the sample again?

**Comment by akacprzak** [comment]
Version 0.0.5 is working fine.
In order to get rid of above is to enable proper Rpi interfaces - you can find them in main menu of device - go to:
Preferences -> Raspberry Pi Configuration -> Interfaces (tab) and enable:
1. I2C 
2. Serial Port
3. Remote GPIO
I had those 3 enabled and its working - maybe there is only I2C interface needed to make it work - I was too lazy to check this out :)

**Comment by LMtx** [comment]
I checked and only **I2C interface** is required for this to work.
